### ISSUE TITLE
Add footer to front page with text2term version, mapper-ui version, and CCB link

### ISSUE THREAD

**Issue by rsgoncalves** [ccb-hms/ontology-mapper-ui#6]
Something like:
> text2term vX.Y.Z. tex2term-gui vI.J.K. 
>This application is developed at the [Center for Computational Biomedicine](https://computationalbiomed.hms.harvard.edu), of the [Harvard Medical School](https://hms.harvard.edu)."

**Comment by paynejason** [comment]
Added in 1.0.0
