### ISSUE TITLE
URL_BASE value should be configurable

### ISSUE THREAD

**Issue by rsgoncalves** [ccb-hms/ontology-mapper-ui#7]
The issue is that the react application hard-codes the `URL_BASE` to be either 'http://localhost:3000' or 'http://127.0.0.0:5000' depending on an environment variable.

This value needs to be configurable in the server/production build, so that the react client delivered to the browser has the correct API endpoint.  In this case, the endpoint needed is [https://text2term.hms.harvard.edu/api/run_mapper](https://text2term.hms.harvard.edu/api/run_mapper).  That is, the `URL_BASE` of [https://text2term.hms.hravard.edu/](https://text2term.hms.hravard.edu/) + the URL [/api/run_mapper](url).

Ideally, this setting should be configurable during the build step **('yarn build' / 'react-scripts build')** so that the runtime .js files deployed to `.../static/build/js` have the appropriate endpoints. 

It looks like this value is configured in 3 places:

```
src/components/MapperForm.js-    // api information
src/components/MapperForm.js:    const URL_BASE =
src/components/MapperForm.js-        process.env.REACT_APP_DOCKER === "true" ? "" : "http://127.0.0.1:5000/";
src/components/MapperForm.js:    const url_mapper = URL_BASE + "/api/run_mapper";
src/components/MapperForm.js:    const url_status = URL_BASE + "/api/current_status";
--
src/components/ResultsForm.js-    // api information
src/components/ResultsForm.js:    const URL_BASE =
src/components/ResultsForm.js-        process.env.REACT_APP_DOCKER === "true" ? "" : "http://127.0.0.1:5000/";
src/components/ResultsForm.js:    const url_submit = URL_BASE + "/api/old_results";
--
src/components/AsyncResults.js-
src/components/AsyncResults.js-    async function getData(processId) {
src/components/AsyncResults.js-    // varies based on local versus Docker
src/components/AsyncResults.js:    const URL_BASE =
src/components/AsyncResults.js-        process.env.REACT_APP_DOCKER === "true"
src/components/AsyncResults.js-            ? "http://localhost:3000/"
src/components/AsyncResults.js-            : "http://127.0.0.1:5000/";
src/components/AsyncResults.js:    const csvURL = new URL(URL_BASE + "/api/download_csv");
src/components/AsyncResults.js:    const jsonURL = new URL(URL_BASE + "/api/download_graph_json");
```

**Comment by paynejason** [comment]
Fixed on the server.
